### ISSUE TITLE
Add instructions and screenshot

### ISSUE THREAD

**Issue by zenorocha** [dracula/coda#1]
Nowadays our site points to https://panic.com/Coda/plugins.php?id=132. We should create instructions and provide screenshot preview.

**Comment by zenorocha** [comment]
@defectivebit can you come up with those instructions and screenshot?

**Comment by briantkatch** [comment]
Screenshot in the repo is still good.

## Install using Panic website

Head over to the Panic website for the one-click install: https://panic.com/coda/plugins.php?id=132

## Install manually

1. Clone the repository locally or use the download ZIP function on GitHub.
2. Copy the `Dracula.sss` to `~/Library/Application Support/Coda 2/Styles` (You can navigate there in Finder by pressing ⇧⌘G and pasting the path).

**Comment by zenorocha** [comment]
Done!! Thanks a lot @defectivebit!

> http://draculatheme.com/coda
